# Generated by Django 3.2.10 on 2021-12-30 08:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='image')),
                ('publish', models.TimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('p', 'منشر شده'), ('d', 'پیش نویس')], max_length=1)),
            ],
        ),
    ]
