# Generated by Django 3.2.10 on 2022-01-29 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20220129_1010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ipaddress',
            old_name='ipaddress',
            new_name='ip_address',
        ),
    ]
